# Ruff config limited to the backend workspace
line-length = 140
target-version = "py312"

[lint]
# Keep it simple for CI: errors & warnings only.
select = ["E", "F"]

# Project-wide ignores:
extend-ignore = [
  "E402",  # module level import not at top of file (we load env early / special cases)
  "E741",  # ambiguous variable name like `l`
]

[lint.per-file-ignores]
# Alembic migrations: allow unused imports, long lines, and import sorting noise
"alembic/versions/*.py" = ["F401", "I001", "E501"]

# Tests: allow unused imports and import-sorting noise
"tests/**/*.py" = ["F401", "I001"]
