"""make course.description nullable

Revision ID: 25de3784cc8a
Revises: 3fbb51b86362
Create Date: 2025-07-26 00:52:32.316400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25de3784cc8a'
down_revision: Union[str, Sequence[str], None] = '3fbb51b86362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('modules_course_id_fkey'), 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key(op.f('modules_course_id_fkey'), 'modules', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
