"""make course.description nullable

Revision ID: 3fbb51b86362
Revises: ac2df2b7fd5b
Create Date: 2025-07-26 00:45:49.971150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fbb51b86362'
down_revision: Union[str, Sequence[str], None] = 'ac2df2b7fd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=160),
               existing_nullable=False)
    op.alter_column('courses', 'description',
               existing_type=sa.TEXT(),
               server_default='',
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('courses', 'description',
               existing_type=sa.String(length=500),
               server_default=None,
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('courses', 'title',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
