# ruff: noqa: F401
"""course job/status fields

Revision ID: c0af4ef7f8e1
Revises: 25de3784cc8a
Create Date: 2025-08-07 17:19:49.028649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0af4ef7f8e1"
down_revision: Union[str, Sequence[str], None] = "25de3784cc8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("task_id", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_courses_task_id"), "courses", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courses_task_id"), table_name="courses")
    op.drop_column("courses", "task_id")
    # ### end Alembic commands ###
